export const batch_all: Record<string, any> = {
  '癸卯': {
    persona: 'Mystic Cyber-Vampire',
    vibe: 'A chill lethality that seeps in unnoticed, nursing fragile sprouts but slowly siphoning the light from its targets.',
    shadow: 'A savior complex demanding permeation everywhere, yet ending up evaporated with nothing in hand.',
    def: 'An artistic phantom spreading surreal, beautiful inspiration from the unseen grid.',
    rel: 'Drenches your wounds with total devotion, but evaporates without a trace the second the connection drops.',
    w: 'Forest flora violently replicates. Hyper-paranoid ego and creativity hijack the network like a neural plague.',
    f: 'Night rain diving into a blast furnace. Chasing fatal wealth loops until the ego evaporates.',
    e: 'Raindrops trapped in mud. Cruel corporate pressure shatters the dreamscape, dragging you to the abyss.',
    m: 'A spine-chillingly accurate database backs your intuition, pulling the cold blade of analysis from behind a frail facade.',
    wa: 'A drizzle becomes a flood. Fluid compliance turns into an obsessive puddle that swallows others whole.'
  },
  '壬寅': {
    persona: 'Melancholic Creator Beast',
    vibe: 'A dreamer shedding lively rain in a jungle where massive dark and predator instincts cross paths.',
    shadow: 'Endless drift and inner void torn between wide-spreading curiosity and an all-consuming impulse.',
    def: 'Prowling the dark mesh. A fierce vitality masked in deep blue sorrow.',
    rel: 'Intensely passionate but abruptly distant, like a sudden storm that vanishes, leaving the partner stranded.',
    w: 'The jungle overgrows. Creative outputs run wild, establishing massive but chaotic new turf.',
    f: 'Sunshine cuts the downpour. Brilliant financial gains burst forth, igniting the wet forest.',
    e: 'A dam tries to hold the monsoon. System rules crash against your wild expansion, causing intense mudslides.',
    m: 'Silver lightning strikes. Sharp logic refines your messy inspiration into a high-tier intellectual dataset.',
    wa: 'The storm intensifies. Pure emotional overload drives you into a ruthless, dominating flood over others.'
  },
  '辛丑': {
    persona: 'Glacial Surgeon',
    vibe: 'Precision surgical tools resting in a block of ice. Moving slow but slicing with flawless, painful accuracy.',
    shadow: 'An obsessive hoarding of grudges and a chilling spite that freezes over any attempt at warmth.',
    def: 'A silent, methodical grinder. You endure the harshest cold to perfect a single, flawless output.',
    rel: 'Demands absolute purity. The slightest glitch in loyalty results in a permanent, cold-blooded severance.',
    w: 'The scalpel carves the frozen wood. Extracting wealth with terrifying patience and lethal precision.',
    f: 'The ice begins to melt. A painful thaw where rigid protocols clash with sudden, passionate disruptions.',
    e: 'Buried in permafrost. Total isolation offline, sinking into deep, dogmatic stubbornness.',
    m: 'Blades sharpen against blades. Teaming with fellow icy rogues to execute a ruthless, unstoppable plan.',
    wa: 'Washing the bloody scalpel in cold water. Perfecting your craft with brilliant, expressive, and icy intellect.'
  },
  '庚子': {
    persona: 'Abyssal Juggernaut',
    vibe: 'Heavy armor sinking into an infinite, cold datastream. Silent power emitting chilling, sonar-like intellect.',
    shadow: 'Total lack of empathy masked as logic, and a paralyzing fear of rusting away in the dark.',
    def: 'A cold, unyielding force cruising the deep web. You process reality with blunt force and sharp water logic.',
    rel: 'Overwhelming possession dragging the partner deep underwater. An unbreakable grip that feels like drowning.',
    w: 'Steel nets sweep the ocean floor. Massively harvesting resources and crypto-assets with ruthless efficiency.',
    f: 'Sonar detects a thermal vent. Sudden visibility and clash with system rules, forcing the mech to adapt or boil.',
    e: 'Trapped in underwater silt. Stubborn reliance on outdated dogmas halts forward momentum completely.',
    m: 'A fleet of submerged mechs syncs up. Brutal collective power flexing its might against the surface world.',
    wa: 'The mech unleashes torpedoes. Expressive, hyper-fluid destruction sweeping away all obstacles through sheer intellect.'
  },
  '己亥': {
    persona: 'Adaptable Shadow Broker',
    vibe: 'A pragmatic dirt patch floating on endless data. Smiling outwardly while secretly siphoning the ocean’s secrets.',
    shadow: 'A deep-seated instability and fear of being washed away, leading to treacherous, shape-shifting lies.',
    def: 'The ultimate survivor who blends into any environment. You casually absorb information and turn it into solid ground.',
    rel: 'A muddy relationship that is hard to escape. Yielding and sweet, but slowly sinking the partner into your rhythm.',
    w: 'Roots plunge deep into the mud island. Harsh external pressures force a rapid, grueling evolution.',
    f: 'The sun bakes the mud solid. External validation and licenses finally give your floating island a permanent anchor.',
    e: 'Expanding the island with stolen dirt. A fierce turf war disguised as a friendly collaboration.',
    m: 'Mining ore from the mud. Sharp, brilliant execution turns your gathered secrets into highly profitable tech.',
    wa: 'The island dissolves into the sea. Total financial windfall, but a risk of losing your core identity in the flood.'
  },
  '戊戌': {
    persona: 'Wasteland Warlord',
    vibe: 'The terrifying aura of a Gwai-gang fortress. A massive, unmoving mountain of dust and stubbornness that crushes dissent.',
    shadow: 'Complete intolerance for differing input, and a paranoid isolation that turns the fortress into a prison.',
    def: 'An unmovable object. You withstand any barrage and impose your own massive, oppressive gravity on the world.',
    rel: 'An iron-handed protector. You offer ultimate security, but leaving the bunker is strictly forbidden.',
    w: 'Battering rams hit the citadel walls. A brutal clash between your stubborn ego and the harsh rules of the megacorp.',
    f: 'Lava flows beneath the citadel. Hidden intellectual power surfaces, enhancing the fortress with terrifying new tech.',
    e: 'The citadel expands into a continent. Peak dominance and an absolute refusal to compromise with anyone.',
    m: 'Opening the gates to deploy mechs. Releasing immense creative and aggressive energy to conquer new markets.',
    wa: 'A moat forms around the fortress. Finally capturing massive wealth, adding a layer of fluid luxury to the dry stone.'
  },
  '丁酉': {
    persona: 'Hyper-Refined Sniper',
    vibe: 'A highly focused, surgical laser etching perfect patterns into cold metal. Flawless, sharp, and blindingly elegant.',
    shadow: 'A hysterical obsession with aesthetics and a cruel tendency to burn anyone who slightly mars the perfection.',
    def: 'You operate with pinpoint accuracy. Every move is calculated, burning through inefficiency to leave only pure value.',
    rel: 'A romance of exact metrics. You provide brilliant warmth but instantly scorch them if they fail a single quality check.',
    w: 'The laser gains unlimited power. A massive influx of data and theory supercharges your flawless execution.',
    f: 'The laser widens into a blast. Fierce competition drives you into a frenzied, destructive race for dominance.',
    e: 'The beam is scattered by dust. Your sharp focus gets bogged down in unnecessary, sprawling side-quests.',
    m: 'Perfecting the platinum circuit. The ultimate window for hitting the jackpot and securing flawless material wealth.',
    wa: 'A cooling mist tries to douse the laser. Enduring strict protocols and corporate suppression, forcing you to stealth your burns.'
  },
  '乙未': {
    persona: 'Wasteland Scavenger',
    vibe: 'A dry, twisted vine clinging to scorched earth. Sustaining life in a White Tiger (Baekho) desert through sheer, bitter willpower.',
    shadow: 'A toxic resentment born of chronic deprivation, prone to lashing out with poisoned thorns when cornered.',
    def: 'The embodiment of painful resilience. You survive where others burn, slowly turning the ash into your own territory.',
    rel: 'Clinging desperately with hidden thorns. You crave moisture but often bleed the one trying to water you.',
    w: 'The thornbush spreads like a plague. Aggressively networking with other survivors to dominate the barren landscape.',
    f: 'The bush catches fire. A spectacular, self-destructive burst of rebellious energy and wild, forbidden thrills.',
    e: 'Roots dig deeper into the dry soil. A ruthless, zero-sum game of competing for the last drops of wealth.',
    m: 'A machete hacks the vines. Severe suppression by the system, forcing you into a painful, restricted compliance.',
    wa: 'A sudden, miraculous rain. The desperate scavenger finally absorbs vital intel and prestige, blooming wildly.'
  },
  '甲午': {
    persona: 'Kamikaze Innovator',
    vibe: 'A massive log thrown into a blazing furnace. Unstoppable kinetic momentum that burns brilliantly until it turns to ash.',
    shadow: 'Complete disregard for sustainability. An addiction to the sprint that inevitably leads to total burnout and self-immolation.',
    def: 'You move fast and break things. A brilliant flash of innovation that commands attention but refuses to slow down.',
    rel: 'A passionate, all-consuming blaze. You burn hot and fast, often leaving the partner holding nothing but cinders.',
    w: 'More wood added to the fire. An unchecked explosion of ego and physical drive that overwhelms all competitors.',
    f: 'The fire peaks and blindingly consumes the wood. Maximum creative output and fame, but extremely high risk of a fatal crash.',
    e: 'The ash settles to fertilize the earth. Converting your reckless momentum into solid, undeniable financial assets.',
    m: 'A steel cage drops on the fire. Agonizing clash with authority as your wild nature is brutally restrained.',
    wa: 'A heavy downpour extinguishes the flames. Forced to cool off, absorbing deep, quiet wisdom in a period of sudden stillness.'
  },
  '甲子': {
    persona: 'Chill Visionary',
    vibe: 'A lone green shoot rising from a freezing, pitch-black ocean. Holding onto a quiet but absolute blueprint for the future.',
    shadow: 'A frosty detachment that observes the world from a high pedestal, masking a deep-seated fear of real emotional connection.',
    def: 'You grow steadily in the dark. Supported by immense hidden intellect, your potential is vast and deeply rooted.',
    rel: 'Cool and somewhat passive. You absorb the partner’s energy like a sponge but remain guarded in your frozen fortress.',
    w: 'The sprout breaks the surface. A massive surge of self-confidence and physical expansion, taking over the network.',
    f: 'The ice thaws, and the plant blooms. Your hidden intellect finally transpires into brilliant, noticeable aesthetic outputs.',
    e: 'Roots hit bedrock. A fierce struggle to extract material wealth from a stubborn, unforgiving corporate structure.',
    m: 'A cold blade prunes the leaves. Strict system regulations force you into a highly disciplined, efficient operational mode.',
    wa: 'The ocean deepens and freezes further. Sinking into overwhelming, dogmatic studies and profound, isolating cyber-trances.'
  },
  '乙丑': {
    persona: 'Tenacious Underdog',
    vibe: 'A frail yet unyielding vine gripping onto a block of ice. Surviving against all odds in the darkest, coldest sludge to bloom a solitary, breathtaking flower.',
    shadow: 'A toxic victim-mentality from enduring too much pain, and a chillingly calculating mindset that trusts no one but its own roots.',
    def: 'The epitome of painful endurance. You bite down and silently weather the harshest storms until your moment finally arrives.',
    rel: 'A heavily guarded heart. You offer deep, almost painful devotion, but subject the partner to endless, silent loyalty tests.',
    w: 'The lotus cracks the ice. Networking with fellow survivors to build a solid support grid out of the frozen wasteland.',
    f: 'The frozen mud finally thaws. Your long-suppressed talents burst into the light, bringing brilliant but shocking disruptions.',
    e: 'Sinking deeper into the sludge. Relentless and obsessive grinding for material wealth, turning every hardship into cold, hard assets.',
    m: 'A scythe trims the vines. Extreme pressure from society forces you to adapt painfully, converting your survival instinct into recognized authority.',
    wa: 'The icy mud turns into a flood. A profound expansion of dark, philosophical intellect that isolates you further from the noisy world.'
  },
  '丙寅': {
    persona: 'Radiant Visionary',
    vibe: 'A blinding morning sun rising above a dense, primal jungle. An infectious, overwhelming brightness backed by the fierce, untamed power of a predator.',
    shadow: 'Reckless impulsivity masked as optimism, and a devastating lack of follow-through once the initial excitement burns out.',
    def: 'An inspiring pioneer who commands the room. Your brilliant ideas and sheer vitality draw people into your orbit like gravity.',
    rel: 'A passionate and dramatic romance. You illuminate the partner’s world completely, but your attention can shift as quickly as the moving sun.',
    w: 'The jungle fuels the sun. Massive acquisition of knowledge and academic credentials forms an unbreakable foundation for your ambitions.',
    f: 'The sun flares into a blinding nova. Unstoppable confidence and leadership hijack the network, placing you at the absolute top of the food chain.',
    e: 'The sun bakes the earth. Your soaring visions are grounded into practical, sprawling projects that yield tangible, though chaotic, results.',
    m: 'Mining gold from the lit terrain. Converting your massive influence into hard, cold capital with sudden, sniper-like precision.',
    wa: 'A sudden monsoon cools the heat. A clash with corporate structure tests your rebel spirit, forcing a painful but necessary maturation.'
  },
  '丁卯': {
    persona: 'Mystic Sensor',
    vibe: 'A flickering, warm candlelight in a dark room full of thorns. Sharp, hyper-sensitive intuition detecting the slightest shifts in the atmosphere.',
    shadow: 'A neurotic, paranoid fragility. Reading too much into everything, creating imaginary enemies, and reacting with sudden, sharp hostility.',
    def: 'An artistic and mystical soul with unparalleled radar. You sense the unseen and navigate the world using subtle, emotional physics.',
    rel: 'A deeply emotional but prickly bond. You crave total sympathetic resonance, but will stab with words if you feel the slightest disconnect.',
    w: 'The candlelight illuminates a vast library. Deep diving into bizarre, esoteric, or underground knowledge systems to build your unique logic.',
    f: 'A sudden flashbang. Unleashing your delicate creativity into a surprisingly aggressive, brilliant display of social dominance.',
    e: 'The candle flickers in a dusty wind. Overextending your bandwidth to help others or express yourself, leading to severe neural exhaustion.',
    m: 'A sharp needle executes the code. Striking exactly when the market is right, converting your esoteric intuitions into sharp financial gains.',
    wa: 'Rain threatens the flame. Overwhelming systemic pressure or authority forces you to retreat into a highly defensive, anxious shell.'
  },
  '戊辰': {
    persona: 'Dormant Titan',
    vibe: 'A massive, seemingly quiet mountain range that contains a mythical beast. A heavy, dominating presence that suddenly erupts with unpredictable, earth-shattering force.',
    shadow: 'A stubbornness as dense as bedrock, and an arrogant belief that everyone else’s logic is inferior to your own.',
    def: 'A self-contained empire. You are incredibly self-reliant, moving slowly but with absolute, crushing momentum when activated.',
    rel: 'You encompass the partner like a mountain over a valley. Overwhelmingly protective, but extremely possessive and unwilling to compromise.',
    w: 'A forest rapidly overtaking the mountain. An intense, stressful clash with authority as you violently resist any attempts to regulate your domain.',
    f: 'Magma heats the deep rock. Absorbing profound ideologies or spiritual concepts, reinforcing your self-belief into an unassailable fortress.',
    e: 'The mountain expands into a continent. Peak dominance and an absolute refusal to compromise, crushing all competitors with sheer mass.',
    m: 'Opening the mountain to mine its core. Releasing massive creative and productive energy, transforming raw potential into flawless tech or output.',
    wa: 'A vast lake forms on the peak. The titan finally secures massive, tangible wealth, bringing a brief moment of fluid luxury to the static stone.'
  },
  '己巳': {
    persona: 'Cunning Observer',
    vibe: 'A seemingly unassuming patch of dry earth hiding a nest of vipers and boiling lava. Sharp, intensely observant, and waiting for the perfect moment to strike.',
    shadow: 'An intense, deep-seated jealousy and a calculating nature that secretly judges everyone while maintaining a polite smile.',
    def: 'A strategic mastermind with immense hidden energy. You gather data quietly and strike only when success is mathematically guaranteed.',
    rel: 'Intensely possessive and observant. You read the partner’s every micro-expression, demanding absolute loyalty while guarding your own secrets.',
    w: 'Vines crack the dry earth. A grueling period of facing strict rules or aggressive competitors, testing your hidden endurance to the limit.',
    f: 'The magma breaks the surface. Receiving massive backing or unexpected inspiration, catapulting your status through sudden, brilliant insight.',
    e: 'Dust storms obscure the horizon. You form temporary, pragmatic alliances to aggressively expand your territory and secure resources.',
    m: 'Forging a blade in the hidden fire. Your quiet observations are executed as flawless, critical outputs that leave others speechless.',
    wa: 'A cold rain hits the hot earth. The perfect moment to convert your strategic plotting into massive, undeniable financial windfalls.'
  },
  '庚午': {
    persona: 'Forged Commander',
    vibe: 'A raw block of titanium being continuously heated and struck into a deadly weapon. The brutal clash of unyielding metal and refining fire.',
    shadow: 'A terrifyingly rigid standard applied to oneself and others, leading to explosive anger when reality fails to meet the strict protocol.',
    def: 'You are an agent of absolute order and pristine execution. Evolving through painful trials to become a sharp, commanding leader.',
    rel: 'A relationship built on respect and strict boundaries. Love is a duty and a command, requiring the partner to meet exceptionally high standards.',
    w: 'The sword cuts through the forest. Ruthlessly securing wealth and resources, driven by an unquenchable thirst for material success.',
    f: 'The furnace heat maxes out. Enduring extreme pressure from society or authority, burning away your flaws to forge a flawless, authoritative identity.',
    e: 'The sword is cooled in the earth. A moment of intellectual pause, absorbing necessary theories and resting before the next battle.',
    m: 'A phalanx of steel weapons assembles. Uniting with fellow hardliners to enforce your rules and violently reshape the environment.',
    wa: 'Quenching the blade in ice water. Your sharp, aggressive nature is brilliantly channeled into expressive, flawless artistic or technical output.'
  },
  '辛未': {
    persona: 'Meticulous Survivor',
    vibe: 'A gleaming, hyper-sharp surgical needle lost in an endless, dry desert. Exquisitely sensitive, critically sharp, and enduring a profoundly lonely environment.',
    shadow: 'A neurotic obsession with finding flaws in everything, and a harsh, cutting tongue that alienates others despite a deep craving for connection.',
    def: 'An analytical genius thriving in barren conditions. You see the finest details and extract value where others see only dust.',
    rel: 'A dry but intensely picky romance. You analyze the partner’s every flaw, demanding an almost impossible level of aesthetic and moral perfection.',
    w: 'The needle strikes a hidden vein. A sudden, sharp acquisition of wealth through meticulous planning and unconventional methods.',
    f: 'The desert sand turns to glass. A painful collision with authority or passion that forces you to dangerously overheat your delicate systems.',
    e: 'A blinding sandstorm. Immersed in profound, slightly twisted intellectual pursuits, using your sharp mind to dissect esoteric truths.',
    m: 'Multiple needles deploy. Forming a cold, efficient network of like-minded critics to dissect and reorganize the chaotic world.',
    wa: 'An oasis in the wasteland. Your hyper-critical energy is finally expressed smoothly, resulting in brilliant, refreshing creative solutions.'
  },
  '壬申': {
    persona: 'Unstoppable Flow',
    vibe: 'A massive torrent of dark water rushing relentlessly through a cold, titanium cavern. Boundless energy endlessly supplied from an unseen, ancient source.',
    shadow: 'An arrogant assumption of superiority and a destructive tendency to wash away anything that tries to limit or direct your flow.',
    def: 'A powerhouse of intellect and stamina. You absorb information rapidly and easily overwhelm obstacles with sheer, persistent force.',
    rel: 'You envelop the partner completamente, offering vast depth but demanding they swim in your current without ever trying to dam it.',
    w: 'The waterfall hits a massive turbine. Converting your immense kinetic energy into brilliant, system-shocking creative expressions.',
    f: 'Steam rises as the water hits hot rock. A frantic, chaotic grab for sudden wealth that sends you into a thrilling, high-risk overdrive.',
    e: 'A massive concrete dam attempts to stop the flow. A bloody, chaotic struggle against structural authority that tries to box you in.',
    m: 'The metal cave expands, increasing the water pressure. A massive influx of data and theory amplifies your intellect to near-omnipotent levels.',
    wa: 'The cave floods completely. Total immersion in chaotic, powerful swarm logic, sweeping away enemies and allies alike in a massive tidal wave.'
  },
  '癸酉': {
    persona: 'Crystal Assassin',
    vibe: 'A perfectly clear drop of poison resting on the edge of a razor-sharp scalpel. Unimaginably pure, intensely sensitive, and silently lethal.',
    shadow: 'A paralyzing germaphobia of the soul, rejecting the messy real world and resorting to cruel, cutting words to protect a fragile core.',
    def: 'An artistic, intuitive genius with zero tolerance for impurity. You perceive the world through a flawless, yet highly critical, lens.',
    rel: 'A romance requiring absolute synchronization. The slightest betrayal or "dirty" behavior results in an instant, icy severance without explanation.',
    w: 'The dew drops onto a toxic flower. Your hyper-sensitive intuition blossoms into bizarre, highly effective creative or technical hacks.',
    f: 'The blade catches the sunlight. A sudden, daring plunge into speculative ventures, risking your pristine status for a thrilling rush of wealth.',
    e: 'Mud splashes the diamond. Forced into uncomfortable compromises with a messy societal structure, causing intense internal stress and disgust.',
    m: 'The blade is polished to perfection. Deep diving into profound, abstract knowledge, refining your intellect into an unassailable, cold weapon.',
    wa: 'The dew joins a freezing rainstorm. Unleashing your chilling intellect alongside a swarm of like-minded rogues, freezing out all opposition.'
  },
  '甲戌': {
    persona: 'Solitary Pioneer',
    vibe: 'A massive, unyielding tree standing alone on a dry, rocky overlook. A lonely but incredibly stubborn presence that refuses to wither despite the lack of water.',
    shadow: 'A rigid dogmatism that rejects all help, and a simmering, explosive frustration from bearing the weight of the world entirely alone.',
    def: 'An independent powerhouse with a fierce work ethic. You rely on nothing but your own deep roots to extract success from the harshest environments.',
    rel: 'You offer immense, sturdy shelter but remain emotionally dry. You demand absolute loyalty and will brutally cut off anyone who threatens your sovereignty.',
    w: 'The oak’s roots shatter the bedrock. Unstoppable expansion of your ego and territory, aggressively crushing any competition in your path.',
    f: 'A forest fire sweeps the hill. Your pent-up energy erupts into a spectacular display of creativity and rebellion, burning down outdated structures.',
    e: 'The hill turns into a mountain of ore. Grinding out massive financial success through sheer, bloody-minded perseverance and strategic hoarding.',
    m: 'A steel axe strikes the trunk. A painful collision with authority, forcing you to endure severe restrictions or fight back with everything you have.',
    wa: 'A miraculous downpour soaks the dry roots. Finally receiving the knowledge and emotional support you secretly craved, allowing for explosive, healthy growth.'
  },
  '乙亥': {
    persona: 'Nomadic Dreamer',
    vibe: 'A tangled mass of kelp floating endlessly on a vast, dark ocean. Adapting to every current while hiding a complex, sprawling network beneath the surface.',
    shadow: 'A severe anchorless anxiety, leading to a tendency to drift away from any solid commitment or reality when things get slightly difficult.',
    def: 'You are the ultimate survivor of the fluid world. You absorb immense knowledge and adapt your shape to survive any environment.',
    rel: 'A deep, consuming dependency hidden behind a flexible exterior. You intertwine completely with the partner, but can untangle and drift away without warning.',
    w: 'The kelp tangles with a massive fleet. Expanding your network aggressively, turning your solitary drift into a coordinated, unstoppable swarm.',
    f: 'The morning sun heats the water. A burst of brilliant, expressive energy finally draws you out of the depths into the spotlight.',
    e: 'Washing ashore on an island. A brief, chaotic struggle to plant roots and claim solid financial ground before the tide pulls you back.',
    m: 'Sharp propellers slice the kelp. A painful encounter with rigid systems or harsh authority, forcing you to sever parts of yourself to survive.',
    wa: 'The ocean becomes a super-storm. Total immersion in profound, isolating philosophical depths, drowning out all external noise.'
  },
  '丙子': {
    persona: 'Beacon in the Dark',
    vibe: 'A blazing, desperately bright lighthouse cutting through a freezing, blinding snowstorm. A fragile yet brilliant warmth holding back an overwhelming dark chill.',
    shadow: 'An exhausting paranoia that the light will fail, leading to frantic, erratic behavior and a tendency to burn out trying to save everyone.',
    def: 'You are a beacon of hope and radical ideas in rigid, cold environments. You attract followers by offering warmth when society is freezing.',
    rel: 'You draw partners out of the darkness, but the intense contrast between your fiery core and the cold world you inhabit makes the relationship extremely volatile.',
    w: 'The lighthouse is heavily fortified with wood. Massive intellectual and institutional backing fuels your flame, making your light unignorable.',
    f: 'A second sun rises. Unstoppable, blinding confidence. You completely dominate the environment, melting the snow and exposing all secrets.',
    e: 'The storm drops heavy mud on the glass. The harsh reality of survival and corporate rules dims your light, forcing you into grueling, practical labor.',
    m: 'A mirrored lens amplifies the beam. Sharp execution turns your warm visions into hyper-efficient, cold, hard cash.',
    wa: 'The blizzard turns into a tidal wave. An absolute struggle against overwhelming systemic pressure; you must rely completely on your inner sparks to survive.'
  },
  '丁丑': {
    persona: 'Enduring Spark',
    vibe: 'A small, incredibly intense forge operating deep inside a frozen cave. Melting the ice drop by drop through pure, agonizing persistence.',
    shadow: 'A deep-seated resentment from constant subterranean struggle, harboring a toxic spite toward those who live easily in the sun.',
    def: 'The ultimate slow-burn operator. You possess terrifying emotional and intellectual stamina, forging your success silently in the dark.',
    rel: 'A relationship of necessary warmth. You provide essential heat, but your frozen exterior requires the partner to chip through walls of ice to reach it.',
    w: 'A massive coal deposit is found. A sudden influx of deep, ancient knowledge supercharges your forge, preparing you for a massive output.',
    f: 'The forge explodes, shattering the cave walls. A spectacular, destructive rebellion against your confined circumstances, declaring your power to the world.',
    e: 'The cave collapses, burying the forge. Sinking into an obsessive, ruthless grind for material wealth, turning all your warmth into cold assets.',
    m: 'Forging a flawless diamond. The perfect alignment of conditions allows you to extract immense, crystalline wealth from the frozen rock.',
    wa: 'A subterranean river floods the forge. Extreme institutional suppression forces you to heavily mask your operations or risk total extinguishment.'
  },
  '己卯': {
    persona: 'Relentless Hacker',
    vibe: 'Sharp blades of grass violently cracking through a solid concrete pavement. A seemingly weak lifeform utilizing terrifying, patient persistence to destroy the structure above it.',
    shadow: 'A chronic, paranoid anxiety and a tendency to execute sudden, ruthless betrayals before anyone else can betray you.',
    def: 'You operate with guerrilla tactics. You find the invisible cracks in any system and relentlessly exploit them until you break through.',
    rel: 'A sharp, sensitive, and deeply painful bond. You constantly test the concrete of the relationship, creating cracks where there were none.',
    w: 'The grass weaves into a massive vine network. Ruthless expansion of power, organizing a grassroots rebellion that overruns the establishment.',
    f: 'The sun bakes the concrete, accelerating the growth. Massive recognition and support for your disruptive ideas, legitimizing your hacker tactics.',
    e: 'Spreading the grass across the entire plaza. You claim massive territory by blending in, creating an inescapable web of influence.',
    m: 'A steel blade trims the grass. A harsh, painful correction by the system, forcing you to retreat and plan your next breach in the shadows.',
    wa: 'A flood washes the concrete away. Sudden, massive financial gains that uproot your entire operation, leading to chaotic but thrilling wealth.'
  },
  '庚辰': {
    persona: 'Stormborn Enforcer',
    vibe: 'A massive, heavily armored dragon soaring through a thunderstorm. A commanding, terrifying presence (Gwai-gang) that dictates the law from above with a voice of thunder.',
    shadow: 'Absolute arrogance and a despotic refusal to admit fault, leading to a lonely reign of terror where no one dares to tell you the truth.',
    def: 'You are an unstoppable force of nature wrapped in logic. When you make a decision, it lands with the weight of a meteor strike.',
    rel: 'An overwhelming, dominating protection. You shelter the partner completely, but the price is absolute, unquestioning submission to your rules.',
    w: 'The dragon hunts in the forest. You violently seize assets and territory, crushing any competition with terrifying efficiency.',
    f: 'A lightning strike supercharges the armor. An extreme clash with authority or a sudden ascension to peak public visibility, risking a fatal overload.',
    e: 'The dragon lands on a mountain of gold. Consolidating immense power and resources, establishing an unassailable fortress of wealth and ego.',
    m: 'A squadron of silver dragons unites. Brutal, synchronized domination of the market, clearing all obstacles through overwhelming collective force.',
    wa: 'The dragon dives into the sea. Pouring your massive energy into brilliant, expressive creation, proving that your power is also elegant and intelligent.'
  },
  '辛巳': {
    persona: 'Lethal Strategist',
    vibe: 'A microscopic, razor-sharp wire strung across a dark hallway, glowing faintly with heat. Invisible, highly sensitive, and capable of a deadly, instantaneous cut when triggered.',
    shadow: 'A paralyzing hypochondria of the mind, obsessing over worst-case scenarios and lashing out violently at imagined threats.',
    def: 'You are the embodiment of precise, cold-blooded execution. You calculate every variable in the shadows and strike only when success is absolute.',
    rel: 'A relationship of high tension and strict boundaries. The partner must navigate the laser grid perfectly; one misstep triggers an explosive, cutting severance.',
    w: 'The wire wraps around a massive tree. A meticulous, slow strangulation of resources, securing long-term wealth through complex, unbreakable contracts.',
    f: 'The wire overheats and snaps. A sudden, catastrophic meltdown caused by overwhelming external pressure, leading to chaotic rebellion.',
    e: 'Dust settles on the wire. A period of deep, almost obsessive studying, refining your lethal logic through ancient or hidden texts.',
    m: 'Deploying a grid of tripwires. Networking with fellow tactical minds to create an inescapable, perfectly controlled environment.',
    wa: 'Cool water resets the system. Your sharp calculations are suddenly expressed with brilliant, refreshing clarity, producing a masterclass of output.'
  },
  '壬午': {
    persona: 'Volatile Maverick',
    vibe: 'A massive reservoir of cold, dark water suddenly superheated from below, erupting into the sky. A breathtaking, violently unstable clash of extreme depths and explosive heat.',
    shadow: 'A chaotic inability to maintain stability. You swing wildly between deep depression and manic expansion, burning bridges in the process.',
    def: 'You possess massive latent power that requires frequent, spectacular release. You operate best in high-stakes, high-adrenaline environments.',
    rel: 'An incredibly passionate but unstable romance. You draw the partner in with deep mystery, then suddenly erupt, overwhelming them with intense, scalding emotion.',
    w: 'The geyser waters a massive jungle. Your explosive energy is captured and channeled into a sprawling, hyper-creative network of projects.',
    f: 'The heat overtakes the water, turning it to steam. Massively successful, high-risk gambles that yield sudden wealth, but require a desperate scramble to hold onto it.',
    e: 'A concrete cap tries to seal the geyser. A violent, explosive clash with corporate structure or societal rules that try to contain your wild nature.',
    m: 'A complex pipeline harnesses the steam. You finally refine your manic energy into a highly structured, profitable, and authoritative system.',
    wa: 'The geyser subsides back into the dark pool. A sudden retreat into deep, isolating intellectualism, recovering your strength in silence.'
  },
  '癸未': {
    persona: 'Illusive Survivor',
    vibe: 'A shimmering pool of water on blistering, cracked earth. Offering the promise of sustenance and depth, but harboring a searing, painful reality beneath the illusion.',
    shadow: 'A deep-seated, cynical resentment born of constant evaporation, leading to deceitful manipulation and a tendency to vanish when relied upon.',
    def: 'You are an incredibly adaptable tactician born in total adversity. You use your sensitivity and illusion to navigate environments that would destroy others.',
    rel: 'A deeply complicated, thirsty bond. You crave emotional hydration but often scorch the partner with hidden anger, keeping them chasing a mirage.',
    w: 'The mirage covers an entire valley. You spread your influence through a massive network of hidden connections, manipulating the environment from the shadows.',
    f: 'The sun hits maximum intensity, vaporizing the water. A desperate, explosive burst of rebellion and creative expression before total exhaustion sets in.',
    e: 'The dry earth cracks further. A brutal, zero-sum struggle to extract material wealth from a completely unforgiving system.',
    m: 'A glass dome captures the vapor. Strict, painful structural rules force you to condense your chaotic energy into recognized, tangible authority.',
    wa: 'A sudden, massive flash flood. Total emotional overflow resulting in sudden intellectual brilliances or a sweeping, destructive takeover of the environment.'
  },
  '甲申': {
    persona: 'Shockwave Pioneer',
    vibe: 'A massive, organic tree wrapped in sparking, industrial cables. A constant, buzzing tension between natural growth and the brutal shock of technological acceleration.',
    shadow: 'A restless, hyperactive anxiety that leads to self-sabotage, aggressively cutting down your own roots before they can fully take hold.',
    def: 'You are a lightning rod for innovation. You thrive on the adrenaline of massive change, combining organic vision with sharp, surgical execution.',
    rel: 'A highly stimulating but shocking relationship. You offer immense growth, but frequently electrocute the partner with sudden, radical shifts in behavior.',
    w: 'The roots expand, shattering the power grid. A massive, aggressive physical expansion, overwhelming competitors with sheer, unstoppable momentum.',
    f: 'The tree catches fire from the sparks. Your innovation turns into spectacular, highly visible artistic or social success, though it burns out quickly.',
    e: 'The cables are grounded into the earth. You finally manage to stabilize your frantic energy, turning your radical ideas into solid, undeniable wealth.',
    m: 'A massive steel frame boxes the tree. High-pressure institutional rules force you into agonizing compliance, threatening to short-circuit your creativity.',
    wa: 'The cables are submerged in cold water. Deep immersion in highly complex, technical dogma, creating a chillingly effective, unstoppable intelligence.'
  },
  '乙酉': {
    persona: 'Delicate Assassin',
    vibe: 'A beautifully fragile flower growing directly out of a sterile, razor-sharp surgical blade. An aesthetic of painful perfection, balancing on the edge of destruction.',
    shadow: 'A hysterical obsession with maintaining the perfect image, accompanied by sudden, incredibly cruel verbal slashes when feeling insecure.',
    def: 'You are a master of high-pressure aesthetics. You endure an extremely harsh environment to produce output that is flawlessly beautiful and razor-sharp.',
    rel: 'A romance on a knife’s edge. You offer exquisite, delicate devotion, but the partner risks being deeply cut if they disturb your precarious balance.',
    w: 'The orchid’s roots dull the blade. Networking with a massive web of allies to overpower the harsh, cutting reality of your environment.',
    f: 'The flower blooms, shattering the steel. A sudden, violent burst of highly expressive, destructive creativity that completely rewrites the rules.',
    e: 'The roots dig into a pile of coins. Obsessive, meticulous grinding to extract tiny flakes of wealth, turning your pain into hard capital.',
    m: 'A second blade strikes the first. An environment of extreme, almost unbearable regulations, forcing you to maintain absolute, flawless discipline to survive.',
    wa: 'A drop of dew softens the edge. You absorb profound, esoteric knowledge, gaining the intellectual power needed to finally control the blade.'
  },
  '丙戌': {
    persona: 'Twilight Guardian',
    vibe: 'The brilliant, melancholic glow of a setting sun over an endless, dusty graveyard (Baekho). A fierce, final burst of warmth defending a desolate territory.',
    shadow: 'A toxic paranoia born from guarding the end of the line, leading to explosive, self-destructive violence when feeling cornered.',
    def: 'A fiercely loyal protector with an immense, hidden reservoir of energy. You shine brightly but carry the heavy responsibility of guarding old secrets.',
    rel: 'You offer the partner your absolute last ray of warmth, fiercely guarding them, but demanding they stay in the graveyard with you.',
    w: 'The sun catches the dry brush. Massive, dangerous expansion of intellectual theories, creating a blazing, chaotic network of ideas.',
    f: 'The sunset turns into a wildfire. A sudden, terrifying explosion of ego and physical energy, violently taking over the environment.',
    e: 'The sun sinks below the dust. Overwhelmingly stubborn isolation, turning your territory into an impenetrable, lonely fortress.',
    m: 'Mining the graves for gold. A ruthless, highly profitable extraction of wealth, converting your fierce protection into hard assets.',
    wa: 'A cold rain falls on the dry earth. Severe clash with authority, putting out your fire and forcing you into a painful, restricted compliance.'
  },
  '丁亥': {
    persona: 'Floating Mystic',
    vibe: 'A single, fragile candle floating on a tiny piece of driftwood across an endless, pitch-black ocean. A surreal, mystical light surviving against overwhelming darkness.',
    shadow: 'A deep-seated neurosis and fear of drowning, leading to highly dependent behavior and a tendency to manipulate others to keep the candle lit.',
    def: 'You possess extremely delicate, otherworldly intuition. You navigate the chaotic world using psychic radar rather than logic.',
    rel: 'A highly romantic, almost desperately dependent bond. You need the partner to shield the wind, and if they fail, your light goes out instantly.',
    w: 'The driftwood anchors to a massive kelp forest. A deep, profound immersion in spiritual or academic theories, feeding the flame steadily.',
    f: 'A sudden burst of fireworks. A shocking, spectacular flash of self-expression and competitive dominance, though very brief.',
    e: 'The candle reaches muddy shores. A grueling attempt to ground your mystical visions into practical reality, causing intense exhaustion.',
    m: 'A silver mirror reflects the flame. Perfect alignment with financial flows, allowing your intuition to pinpoint and extract pure wealth effortlessly.',
    wa: 'A rogue wave crashes down. Painfully adapting to strict, overwhelming systemic rules, forcing your light to operate entirely underwater.'
  },
  '己丑': {
    persona: 'Glacial Endurer',
    vibe: 'An endless expanse of rock-hard, frozen soil. Deeply pragmatic, moving at a glacial pace, but possessing an unstoppable, crushing mass.',
    shadow: 'An intense, bitter hoarding of grudges and a stubborn refusal to change course, even when heading directly for a cliff.',
    def: 'You are the absolute master of slow, painful endurance. You survive conditions that destroy others by freezing your emotions and focusing on pure utility.',
    rel: 'A heavy, cold responsibility. You provide unshakeable stability, but demand the partner endure the frozen wasteland with you without complaining.',
    w: 'A forest tries to take root in the permafrost. A violent, stressful clash against competitors, violently defending your frozen turf.',
    f: 'Geothermal heat thaws the ground. Sudden, massive support or inspiration finally melts your rigid exterior, allowing you to bloom.',
    e: 'The tundra expands infinitely. A relentless, obsessive hoarding of resources and territory, isolating yourself in a fortress of frozen dirt.',
    m: 'Mining deep into the frozen rock. Releasing your pent-up observations into a highly critical, flawless, and profitable system.',
    wa: 'An icy river carves the stone. Massive philosophical or strategic intellect floods in, enhancing your survival tactics into a terrifyingly effective machine.'
  },
  '庚寅': {
    persona: 'Predatory Lumberjack',
    vibe: 'A massive, roaring chainsaw tearing through a dense, primal jungle. Brutal, loud, and incredibly effective, driven by a raw, aggressive instinct to conquer.',
    shadow: 'Severe impatience and a tendency to recklessly destroy valuable resources because you cannot stop the machine once it starts.',
    def: 'You are a force of pure, aggressive kinetic action. You don’t analyze the problem; you cut it down and turn it into lumber.',
    rel: 'A dominant, overpowering approach to love. You aggressively claim your partner, offering massive security but leaving little room for subtlety.',
    w: 'The chainsaw hits a massive redwood. A spectacular, high-risk battle for immense wealth, taking on the biggest targets with fearless aggression.',
    f: 'The engine overheats and catches fire. A sudden, dangerous clash with authority or public exposure that forces a chaotic recalibration of your power.',
    e: 'The blade dulls against rock. Grinding out practical success through sheer, bloody-minded perseverance, converting your aggression into steady assets.',
    m: 'A fleet of chainsaws syncs up. Terrifying market dominance as you ally with other heavy hitters to completely rewrite the rules of the game.',
    wa: 'Cooling the engine in a river. A moment of fluid, brilliant strategic expression, refining your blunt force into a surprisingly elegant, lethal art.'
  },
  '辛卯': {
    persona: 'Surgical Pruner',
    vibe: 'A pair of gleaming, razor-sharp silver scissors meticulously cutting through wild, overgrown weeds. Delicate, hyper-focused, and obsessed with maintaining the perfect aesthetic boundary.',
    shadow: 'A neurotic obsession with micromanagement and a hysterical tendency to snip away anything—or anyone—that ruins the visual harmony.',
    def: 'You are an absolute perfectionist. You possess a critically sharp eye for detail and effortlessly sever inefficiency to create a pristine reality.',
    rel: 'A heavily curated romance. You clip away the partner’s flaws, which feels like elegant care but is actually a deeply controlling demand for aesthetic perfection.',
    w: 'The scissors attack a massive, tangled vine. A sharp, high-speed acquisition of wealth and resources through highly critical, zero-margin-for-error networking.',
    f: 'The silver melts in the sun. A painful, shocking subjection to harsh authority or overwhelming passion that ruins your perfect control.',
    e: 'Burying the scissors in the dirt. Enduring a period of forced humility and deep study to regain your lost sharpness.',
    m: 'A collection of scalpels unites. Forming an elite, hyper-critical clique that surgically dominates the social or professional environment.',
    wa: 'Washing the blades in clear water. A brilliant, refreshing burst of creativity, expressing your sharp intellect through flawless, elegant output.'
  },
  '壬辰': {
    persona: 'Abyssal Overlord',
    vibe: 'A massive, dark tsunami crashing violently over a crumbling concrete dam. The terrifying, unstoppable force of the deep (Gwai-gang) overwhelming all structural limits.',
    shadow: 'A tyrannical god-complex and a devastatingly destructive anger that drowns allies and enemies alike when denied what it wants.',
    def: 'You are an overwhelming force of nature. You harbor immense, deep intellect and power, waiting for the perfect moment to flood the landscape.',
    rel: 'A deeply possessive, all-consuming flood. You drown the partner in your depths, offering a vast, mysterious world, but demanding total surrender to your current.',
    w: 'The wave crashes into a huge forest. Massively expanding your creative output, tearing down old structures to establish your own chaotic empire.',
    f: 'A volcano erupts underwater. Shocking, violent extraction of massive wealth through high-risk, world-shaking gambles.',
    e: 'The dam tries to hold the water. A brutal, grinding conflict with systemic authority that tries to box in your infinite volume.',
    m: 'The water pressure crystallizes the stone. An extreme amplification of your strategic intellect, giving you the cold logic to rule permanently.',
    wa: 'The entire world floods. Total, unstoppable immersion in collective power, washing away individuality for ultimate, terrifying dominion.'
  },
  '癸巳': {
    persona: 'Fluid Infiltrator',
    vibe: 'A subtle, misty rain falling silently over a hot, venomous jungle. Seeping into every crack unnoticed while quietly calculating the perfect strike.',
    shadow: 'Intense, hidden jealousy and a manipulative tendency to subtly poison the environment while playing the innocent victim.',
    def: 'You are a master of soft power. You adapt flawlessly to your surroundings, using high emotional intelligence and hidden strategy to get exactly what you want.',
    rel: 'A deeply subtle, enveloping bond. You figure out the partner’s exact weak points and wrap around them softly, making them entirely dependent on your rain.',
    w: 'The mist waters the venomous vines. A highly effective, quiet expansion of your network, manipulating others to do your heavy lifting.',
    f: 'The sun pierces the mist. A sudden, stunning display of your hidden talents, converting your quiet strategy into massive, visible financial gain.',
    e: 'The rain hits dry clay. Enduring harsh scrutiny and structural pressure, forcing you to disguise your motives even deeper.',
    m: 'A silver blade cuts through the mist. Deep, rigorous study and intellectual reinforcement turn your soft strategy into an unbreakable, sharp logic.',
    wa: 'The mist turns into a monsoon. Dropping the stealth act for an overwhelming flood of emotional and intellectual domination.'
  },
  '戊寅': {
    persona: 'Untamed Sovereign',
    vibe: 'A massive, unmoving mountain surrounded by a chaotic, roaring jungle filled with predators. Extreme, stoic stubbornness clashing with wild, violent energy.',
    shadow: 'A terrifying inability to compromise, often resulting in explosive, destructive outbursts when the jungle tries to overrun the mountain.',
    def: 'You possess massive scale and an aggressive, pioneering spirit. You stand firm in the middle of chaos, imposing your heavy will on the environment.',
    rel: 'You are a massive, protective presence, but incredibly demanding. The partner must live in your jungle and abide strictly by the laws of your mountain.',
    w: 'The forest violently attacks the stone. An intense, brutal struggle for dominance against harsh competitors or rigid rules.',
    f: 'Magma erupts from the peak. Breathtaking intellectual power surfaces, establishing your authority and blinding anyone who doubted your vision.',
    e: 'The mountain range expands. Absolute, unwavering stubbornness and a massive consolidation of territory and ego.',
    m: 'Mining the mountain to forge weapons. Turning your massive scale into sharp, calculated, and highly profitable outputs.',
    wa: 'A huge lake forms at the base. You finally harness your chaotic energy, securing massive, tangible wealth to add luxury to your kingdom.'
  },
  '戊子': {
    persona: 'Silent Hoarder',
    vibe: 'A massive, barren mountain of ice hiding a vast, subterranean lake of dark water. An immovable, stoic exterior concealing incredibly complex, secretive calculations.',
    shadow: 'A deep, paralyzing paranoia about losing resources, leading to obsessive stinginess and a total emotional freeze toward the suffering of others.',
    def: 'You are the ultimate practical strategist. You show the world a boring, unyielding rock, while secretly moving massive currents of wealth in the dark.',
    rel: 'You offer immense, stable protection, but the partner will never truly know the depths of the underground lake. Emotionally dry but pragmatically dependable.',
    w: 'Roots crack the icy stone. A painful, stressful confrontation with ambitious competitors trying to tap into your hidden lake.',
    f: 'The sun tries to melt the peak. Absorbing intense, necessary academic knowledge to legitimize your hidden operations.',
    e: 'The mountain grows larger. A sheer, brutal force of will aimed solely at accumulating more territory and freezing out rivals.',
    m: 'Drilling into the ice for pure water. A flawless, hyper-efficient system is deployed to extract maximum wealth from minimum effort.',
    wa: 'The hidden lake overflows. Your secretive wealth is finally exposed, leading to a massive, chaotic deluge of financial power and risk.'
  },
  '丙申': {
    persona: 'Brilliant Opportunist',
    vibe: 'A spectacular, high-energy laser show bouncing off the walls of a cold, solid metal vault. Blinding creativity colliding with extremely sharp, practical calculation.',
    shadow: 'A frantic inability to sit still, constantly chasing the next shiny object, leaving a trail of half-finished, loudly advertised failures.',
    def: 'You are a genius of the spotlight. You possess massive, infectious energy combined with a surgical ability to spot exactly where the money is.',
    rel: 'A highly entertaining, fast-paced romance. You dazzle the partner completely, but your attention is notoriously short, always seeking the next thrill.',
    w: 'The vault fills with complex wiring. A massive, slightly chaotic influx of intellectual power that supercharges your lasers.',
    f: 'The lasers combine into a death ray. Unstoppable, blinding confidence that completely dominates the social and professional sphere.',
    e: 'Dust settles in the vault. A grounding period where your frantic energy is forced to build solid, lasting infrastructure.',
    m: 'The vault doors lock perfectly. Achieving the ultimate goal: massive, undeniable, and perfectly secured material wealth.',
    wa: 'The vault floods with dark water. A painful, shocking collision with strict authority, forcing you to turn off the show and survive in silence.'
  },
  '壬戌': {
    persona: 'Abyssal Nomad',
    vibe: 'A massive, dark river violently carving its way through a dry, unforgiving canyon (Baekho). Unstoppable momentum crashing through absolute, rock-hard stubbornness.',
    shadow: 'A terrifying, explosive anger when the flow is blocked, leading to a violent tendency to wash away allies and enemies in a fit of rage.',
    def: 'You are a force of profound intellect and destructive perseverance. You endure the harshest, driest environments by relying on your deep, hidden reserves.',
    rel: 'A relationship of necessary survival. You offer deep water in a dry land, but demand absolute loyalty, destroying the connection instantly if betrayed.',
    w: 'The river nourishes a hidden forest. Your massive, pent-up energy births a highly creative, sprawling network of new alliances.',
    f: 'Lava flows into the river. A spectacular, dangerous burst of sudden wealth and extreme, high-stakes gambles.',
    e: 'The canyon walls collapse. A brutal, bloody conflict with the system, testing your ability to survive total structural failure.',
    m: 'The river unearths a gold mine. A flawless integration of your fluid intellect with the hard reality of money, yielding massive profits.',
    wa: 'The river becomes a flood. Total immersion in overwhelming power, washing away the canyon and establishing an absolute monarchy of the deep.'
  }
};
