
export const BAZI_MAPPING = {
  tenGods: {
    "비견": { ko: "비견", en: "The Mirror", desc: "Your twin energy. Reflective and independent." },
    "比肩": { ko: "비견", en: "The Mirror", desc: "Your twin energy. Reflective and independent." },
    "겁재": { ko: "겁재", en: "The Rival", desc: "Competitive edge. High stakes, high energy." },
    "劫财": { ko: "겁재", en: "The Rival", desc: "Competitive edge. High stakes, high energy." },
    "식신": { ko: "식신", en: "The Artist", desc: "Creative flow. Natural talent and expression." },
    "食神": { ko: "식신", en: "The Artist", desc: "Creative flow. Natural talent and expression." },
    "상관": { ko: "상관", en: "The Rebel", desc: "Rules? What rules? Disruptive and brilliant." },
    "伤官": { ko: "상관", en: "The Rebel", desc: "Rules? What rules? Disruptive and brilliant." },
    "편재": { ko: "편재", en: "The Maverick", desc: "Unconventional wealth. Big risks, big rewards." },
    "偏财": { ko: "편재", en: "The Maverick", desc: "Unconventional wealth. Big risks, big rewards." },
    "정재": { ko: "정재", en: "The Architect", desc: "Steady growth. Building your empire brick by brick." },
    "正财": { ko: "정재", en: "The Architect", desc: "Steady growth. Building your empire brick by brick." },
    "편관": { ko: "편관", en: "The Warrior", desc: "Intense pressure. Forged in fire, born to lead." },
    "七杀": { ko: "편관", en: "The Warrior", desc: "Intense pressure. Forged in fire, born to lead." },
    "정관": { ko: "정관", en: "The Judge", desc: "Order and status. Respecting the cosmic law." },
    "正官": { ko: "정관", en: "The Judge", desc: "Order and status. Respecting the cosmic law." },
    "편인": { ko: "편인", en: "The Mystic", desc: "Esoteric knowledge. Seeing what others miss." },
    "偏印": { ko: "편인", en: "The Mystic", desc: "Esoteric knowledge. Seeing what others miss." },
    "정인": { ko: "정인", en: "The Sage", desc: "Traditional wisdom. Nurtured by the ancestors." },
    "正印": { ko: "정인", en: "The Sage", desc: "Traditional wisdom. Nurtured by the ancestors." },
  },
  elements: {
    "Wood": { ko: "목 (Wood)", en: "Wood", color: "#4ADE80", vibe: "Growth & Vitality" },
    "Fire": { ko: "화 (Fire)", en: "Fire", color: "#F87171", vibe: "Passion & Intensity" },
    "Earth": { ko: "토 (Earth)", en: "Earth", color: "#FACC15", vibe: "Stability & Grounding" },
    "Metal": { ko: "금 (Metal)", en: "Metal", color: "#E2E8F0", vibe: "Precision & Clarity" },
    "Water": { ko: "수 (Water)", en: "Water", color: "#60A5FA", vibe: "Wisdom & Flow" },
  },
  stems: {
    "甲": { ko: "갑목", en: "Yang Wood", element: "Wood" },
    "乙": { ko: "을목", en: "Yin Wood", element: "Wood" },
    "丙": { ko: "병화", en: "Yang Fire", element: "Fire" },
    "丁": { ko: "정화", en: "Yin Fire", element: "Fire" },
    "戊": { ko: "무토", en: "Yang Earth", element: "Earth" },
    "己": { ko: "기토", en: "Yin Earth", element: "Earth" },
    "庚": { ko: "경금", en: "Yang Metal", element: "Metal" },
    "辛": { ko: "신금", en: "Yin Metal", element: "Metal" },
    "壬": { ko: "임수", en: "Yang Water", element: "Water" },
    "癸": { ko: "계수", en: "Yin Water", element: "Water" },
  },
  branches: {
    "子": { ko: "자수", en: "Rat", element: "Water" },
    "丑": { ko: "축토", en: "Ox", element: "Earth" },
    "寅": { ko: "인목", en: "Tiger", element: "Wood" },
    "卯": { ko: "묘목", en: "Rabbit", element: "Wood" },
    "辰": { ko: "진토", en: "Dragon", element: "Earth" },
    "巳": { ko: "사화", en: "Snake", element: "Fire" },
    "午": { ko: "오화", en: "Horse", element: "Fire" },
    "未": { ko: "미토", en: "Goat", element: "Earth" },
    "申": { ko: "신금", en: "Monkey", element: "Metal" },
    "酉": { ko: "유금", en: "Rooster", element: "Metal" },
    "戌": { ko: "술토", en: "Dog", element: "Earth" },
    "亥": { ko: "해수", en: "Pig", element: "Water" },
  }
};
